package com.cloudimage.app.ui.theme

import androidx.compose.ui.graphics.Color

// Brand: deep teal — calm, paper-like, distinct from wallpaper-app clichés.

val md_light_primary = Color(0xFF006A6B)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFF9CF1F1)
val md_light_onPrimaryContainer = Color(0xFF002021)
val md_light_secondary = Color(0xFF4A6365)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFCCE8E9)
val md_light_onSecondaryContainer = Color(0xFF051F20)
val md_light_tertiary = Color(0xFF4B607C)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFD3E4FF)
val md_light_onTertiaryContainer = Color(0xFF041C35)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFF7FAFA)
val md_light_onBackground = Color(0xFF171C1C)
val md_light_surface = Color(0xFFFAFDFD)
val md_light_onSurface = Color(0xFF171C1C)
val md_light_surfaceVariant = Color(0xFFDBE4E4)
val md_light_onSurfaceVariant = Color(0xFF3F4949)
val md_light_outline = Color(0xFF6F7979)
val md_light_outlineVariant = Color(0xFFBEC8C8)
val md_light_inverseSurface = Color(0xFF2B3131)
val md_light_inverseOnSurface = Color(0xFFECEFEF)
val md_light_inversePrimary = Color(0xFF80D4D6)
val md_light_scrim = Color(0xFF000000)

val md_dark_primary = Color(0xFF80D4D6)
val md_dark_onPrimary = Color(0xFF003737)
val md_dark_primaryContainer = Color(0xFF004F50)
val md_dark_onPrimaryContainer = Color(0xFF9CF1F1)
val md_dark_secondary = Color(0xFFB0CBCB)
val md_dark_onSecondary = Color(0xFF1B3435)
val md_dark_secondaryContainer = Color(0xFF324B4C)
val md_dark_onSecondaryContainer = Color(0xFFCCE8E9)
val md_dark_tertiary = Color(0xFFB3C8E8)
val md_dark_onTertiary = Color(0xFF1A3050)
val md_dark_tertiaryContainer = Color(0xFF334869)
val md_dark_onTertiaryContainer = Color(0xFFD3E4FF)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF141A1A)
val md_dark_onBackground = Color(0xFFDFE4E4)
val md_dark_surface = Color(0xFF141A1A)
val md_dark_onSurface = Color(0xFFDFE4E4)
val md_dark_surfaceVariant = Color(0xFF3F4949)
val md_dark_onSurfaceVariant = Color(0xFFBEC8C8)
val md_dark_outline = Color(0xFF899393)
val md_dark_outlineVariant = Color(0xFF3F4949)
val md_dark_inverseSurface = Color(0xFFDFE4E4)
val md_dark_inverseOnSurface = Color(0xFF2B3131)
val md_dark_inversePrimary = Color(0xFF006A6B)
val md_dark_scrim = Color(0xFF000000)
